<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.9.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.0" />    
    <PackageReference Include="Faster.Modulith.Contracts" Version="1.0.*" />
    <PackageReference Include="Faster.Modulith.Analyzers" Version="1.0.6" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Application\EventHandlers\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Module.Membership.Api\Module.Membership.Api.csproj" />
  </ItemGroup>
</Project>

