<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules\Module.Employee\Module.Employee.Api\Module.Employee.Api.csproj" />
    <ProjectReference Include="..\Modules\Module.Employee\Module.Employee\Module.Employee.csproj" />
    <ProjectReference Include="..\modules\Module.Feedback\Module.Feedback.Api\Module.Feedback.Api.csproj" />
    <ProjectReference Include="..\modules\Module.Feedback\Module.Feedback\Module.Feedback.csproj" />
    <ProjectReference Include="..\Modules\Module.Inventory\Module.Inventory.Api\Module.Inventory.Api.csproj" />
    <ProjectReference Include="..\Modules\Module.Inventory\Module.Inventory\Module.Inventory.csproj" />
    <ProjectReference Include="..\Modules\Module.Kitchen\Module.Kitchen.Api\Module.Kitchen.Api.csproj" />
    <ProjectReference Include="..\Modules\Module.Kitchen\Module.Kitchen\Module.Kitchen.csproj" />
    <ProjectReference Include="..\Modules\Module.Loyalty\Module.Loyalty.Api\Module.Loyalty.Api.csproj" />
    <ProjectReference Include="..\Modules\Module.Loyalty\Module.Loyalty\Module.Loyalty.csproj" />
    <ProjectReference Include="..\Modules\Module.Marketing\Module.Marketing.Api\Module.Marketing.Api.csproj" />
    <ProjectReference Include="..\Modules\Module.Marketing\Module.Marketing\Module.Marketing.csproj" />
    <ProjectReference Include="..\Modules\Module.Ordering\Module.Ordering.Api\Module.Ordering.Api.csproj" />
    <ProjectReference Include="..\Modules\Module.Ordering\Module.Ordering\Module.Ordering.csproj" />
  </ItemGroup>

</Project>
