<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Faster.Modulith.Analyzers" Version="1.0.0" />
    <PackageReference Include="Faster.Modulith.Contracts" Version="1.0.0" />
    
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules\Module.Facilities\Module.Facilities.Api\Module.Facilities.Api.csproj" />
    <ProjectReference Include="..\Modules\Module.Facilities\Module.Facilities\Module.Facilities.csproj" />
    <ProjectReference Include="..\Modules\Module.HumanResources\Module.HumanResources.Api\Module.HumanResources.Api.csproj" />
    <ProjectReference Include="..\Modules\Module.HumanResources\Module.HumanResources\Module.HumanResources.csproj" />
    <ProjectReference Include="..\Modules\Module.IdentityAccess\Module.IdentityAccess.Api\Module.IdentityAccess.Api.csproj" />
    <ProjectReference Include="..\Modules\Module.IdentityAccess\Module.IdentityAccess\Module.IdentityAccess.csproj" />
  </ItemGroup>



</Project>
