using Faster.Modulith;

var builder = WebApplication.CreateBuilder(args);

// --- 1. FRAMEWORK SETUP ---
builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new() { Title = "Modular Monolith API", Version = "v1" });
});

// Add Logging so we can see the "Console.WriteLine" output from the modules
builder.Services.AddLogging(logging => logging.AddConsole());

// --- 2. CORE ARCHITECTURE SETUP ---
// Registers: IOrchestrator, IUseCaseDispatcher, IEventDispatcher, IServiceScopeFactory

builder.Services.AddModulith();

// --- 3. MODULE REGISTRATION ---
// These methods are generated by the Source Generator based on the "internal" classes found.

builder.Services.AddHumanResourcesModule();
builder.Services.AddIdentityAccessModule();
builder.Services.AddFacilitiesModule();

var app = builder.Build();

// --- 4. PIPELINE SETUP ---
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();
app.UseAuthorization();
app.MapControllers();

app.Run();