<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Faster.Modulith.Analyzers" Version="1.1.3" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\modules\Module.Membership.Api\Module.Membership.Api.csproj" />
    <ProjectReference Include="..\..\modules\Module.Membership\Module.Membership.csproj" />
    <ProjectReference Include="..\..\modules\Module.Offers.Api\Module.Offers.Api.csproj" />
    <ProjectReference Include="..\..\modules\Module.Offers\Module.Offers.csproj" />
    <ProjectReference Include="..\..\modules\Module.Reports.Api\Module.Reports.Api.csproj" />
    <ProjectReference Include="..\..\modules\Module.Reports\Module.Reports.csproj" />
  </ItemGroup>

</Project>
