using System;
using System.Collections.Generic;
using System.Text;

// NOTICE: This is in 'Module.IdentityAccess.Infrastructure'.
// It is the implementation detail that allows our application to talk to the "Outside World" (Active Directory).
namespace Module.IdentityAccess.Infrastructure;

/// <summary>
/// A wrapper (Gateway) around the external Active Directory system.
/// <para>
/// <b>Why exists?</b> We don't want to sprinkle complex LDAP (Lightweight Directory Access Protocol) 
/// connection code throughout our application. We centralize it here. 
/// If we switch from On-Premise AD to Azure AD later, we only have to rewrite this one class.
/// </para>
/// </summary>
internal class ActiveDirectoryGateway
{
    /// <summary>
    /// Provisions a new user in the external system.
    /// </summary>
    /// <param name="name">The full name of the employee.</param>
    /// <returns>The email address generated by the AD system.</returns>
    public async Task<string> CreateUserAsync(string name)
    {
        // SIMULATION: Network Latency
        // Calling an external server is slow. We simulate that delay here.
        await Task.Delay(50);

        // LOGIC: Email Generation
        // In a real scenario, Active Directory might have complex rules (e.g., ensure uniqueness, 
        // handle duplicates like 'john.smith2', remove accents, handle apostrophes).
        // CRITIQUE: Fragile Logic.
        // Replacing " " with "." is a good start, but what about "O'Connor"? 
        // The resulting email "o'connor@corp.com" might be invalid on some servers.
        // Production code needs robust "Slugification" logic here.
        var email = $"{name.Replace(" ", ".").ToLower()}@corp.com";

        // OBSERVABILITY:
        // We log exactly what happened so admins can debug "Why didn't John get an email?"
        Console.WriteLine($"[AD Gateway] Account Provisioned: {email}");

        return email;
    }
}