<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.9.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.0" />       
    <PackageReference Include="Faster.Modulith.Analyzers" Version="1.1.2" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Application\UseCases\" />
    <Folder Include="Application\EventHandlers\" />
    <Folder Include="Application\CommandHandlers\" />
    <Folder Include="Contracts\" />
    <Folder Include="Domain\" />
    <Folder Include="Infrastructure\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Module.MyFirstModule.Api\Module.MyFirstModule.Api.csproj" />
  </ItemGroup>
</Project>

