<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>Faster.Modulith.Contracts</PackageId>
    <Description>Building unbreakable monoliths with rosyln sourcegenerators</Description>
    <RepositoryUrl>https://github.com/Wsm2110/Faster.Modulith</RepositoryUrl>
    <Version>1.0.4</Version>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Description>
      A high-performance framework for building unbreakable modular monoliths in .NET.
      Uses Roslyn Source Generators to enforce strict architectural boundaries and eliminate dispatching boilerplate at compile-time.
      Ensuring the final feature is implemented as seamlessly as the first.
    </Description>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.1" />
  </ItemGroup>
</Project>