using System;
using System.Collections.Generic;
using System.Text;

// NOTICE: This is in the Infrastructure layer.
// This is where code that touches the "Real World" lives (File System, Network, USB Devices).
namespace Module.Facilities.Infrastructure;

/// <summary>
/// The "Driver" class that knows how to talk to the physical badge printer.
/// <para>
/// <b>Why exists?</b> Your business logic (Application Layer) should not know about USB ports or Printer Drivers.
/// By wrapping that complexity here, the rest of the app just calls "PrintBadge" and doesn't care if 
/// the printer is a Zebra ZP450 or a PDF generator.
/// </para>
/// </summary>
internal class SmartCardSystem
{
    /// <summary>
    /// Sends a print command to the hardware.
    /// </summary>
    /// <param name="name">The text to print on the card.</param>
    /// <returns>The unique badge ID generated by the hardware.</returns>
    public async Task<string> PrintBadgeAsync(string name)
    {
        // SIMULATION: Real hardware is slow.
        // We use Task.Delay to mimic the 200ms it takes for the printer to receive the signal.
        // This forces the calling code to be 'async' and handle waiting properly.
        await Task.Delay(200);

        // LOGIC: Generating a fake "Unique Badge Code".
        // .GetHashCode() turns the name into a number.
        // :X formats that number as Hexadecimal (e.g., 1A3F).
        var code = $"BADGE-{name.GetHashCode():X}";

        // SIDE EFFECT:
        // This is the actual "work" happening in the physical world.
        Console.WriteLine($"[Hardware] 🖨️ Printing Badge for {name}: {code}");

        return code;
    }
}