using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;
using System.Text.RegularExpressions;

namespace Faster.Modulith.Analyzers.Generators;

/// <summary>
/// Generates a C4 Level 3 Component Diagram using Mermaid syntax.
/// This generator visualizes the internal structure of modules, including Use Cases, 
/// Commands, Events, Dispatchers, and their inter-dependencies.
/// </summary>
internal static class DiagramGenerator
{
    /// <summary>
    /// Generates the Mermaid diagram source code and adds it to the production context.
    /// </summary>
    /// <param name="context">The source production context to output the generated file.</param>
    /// <param name="modules">The list of referenced module assemblies to scan.</param>
    /// <param name="hostAssemblyName">The name of the hosting assembly (e.g., the API project).</param>
    public static void Generate(SourceProductionContext context, List<IAssemblySymbol> modules, string hostAssemblyName)
    {
        var sb = new StringBuilder();

        // ---------------------------------------------------------
        // 1. Header & Styles
        // ---------------------------------------------------------
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// C4 LEVEL 3: COMPONENT DIAGRAM - RECURSIVE TRACE FIXED");
        sb.AppendLine($"// Generated at: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine("/*");
        sb.AppendLine("    graph TD");

        // Define Mermaid class styles for different artifact types
        sb.AppendLine("    classDef endpoint fill:#4caf50,stroke:#2e7d32,stroke-width:2px,color:white;");
        sb.AppendLine("    classDef handler fill:#7e57c2,stroke:#4a148c,stroke-width:2px,color:white;");
        sb.AppendLine("    classDef command fill:#ab47bc,stroke:#6a1b9a,stroke-width:1px,color:white;");
        sb.AppendLine("    classDef dispatcher fill:#ff9800,stroke:#e65100,stroke-width:2px,color:black;");
        sb.AppendLine("    classDef eventNode fill:#ffeb3b,stroke:#fbc02d,stroke-width:2px,color:black;");
        sb.AppendLine("    classDef db fill:#efebe9,stroke:#4e342e,stroke-width:2px,shape:cylinder;");
        sb.AppendLine("    classDef facade fill:#e3f2fd,stroke:#1565c0,stroke-width:2px;");
        sb.AppendLine("    classDef external fill:#eceff1,stroke:#546e7a,stroke-width:2px,stroke-dasharray: 5 5;");

        // ---------------------------------------------------------
        // 2. Data Loading & Parsing
        // ---------------------------------------------------------
        var allModuleData = new Dictionary<string, List<HandlerInfo>>();

        foreach (var module in modules)
        {
            // Extract module name using Regex to handle "Modules.Ordering" or "Ordering.Module" naming conventions
            var match = Regex.Match(module.Name, @"(?:^|\.)Modules?\.(\w+)", RegexOptions.IgnoreCase);
            string modName = match.Success ? match.Groups[1].Value : module.Name.Split('.').Last();

            // Skip infrastructure-only or contract-only assemblies to keep the diagram focused
            if (modName.Equals("Contracts", StringComparison.OrdinalIgnoreCase) ||
                modName.Equals("Abstractions", StringComparison.OrdinalIgnoreCase))
                continue;

            if (!allModuleData.ContainsKey(modName))
                allModuleData[modName] = new List<HandlerInfo>();

            // Use the Scanner to extract all UseCases, Commands, and Events from the assembly
            allModuleData[modName].AddRange(Scanner.ScanAssembly(module));
        }

        // Sort modules to ensure the diagram layout is deterministic (stable) across builds
        var sortedModules = allModuleData.OrderBy(x => x.Key).ToList();

        // ---------------------------------------------------------
        // 3. Node Generation (Subgraphs)
        // ---------------------------------------------------------
        foreach (var kvp in sortedModules)
        {
            string modName = kvp.Key;
            var items = kvp.Value;
            bool moduleHasDb = false;

            // Create a subgraph container for the Module
            sb.AppendLine($"    subgraph {modName}_Module [Container: {modName} Module]");
            sb.AppendLine("        direction TB");

            // Define the infrastructure nodes (Dispatcher & Facade)
            string dispatcherNode = $"Dispatcher_{modName}";
            sb.AppendLine($"        {dispatcherNode}{{{modName} Dispatcher}}:::dispatcher");
            string facadeNode = $"Facade_{modName}";
            sb.AppendLine($"        {facadeNode}([I{modName}Module]):::facade");

            // Generate nodes for UseCases and Handlers
            foreach (var h in items.Where(x => x.IsHandler))
            {
                string nodeId = $"{modName}_{h.HandlerSimpleName}";
                string style = h.Type == ArtifactType.UseCase ? "handler" : "command";
                string label = h.Type == ArtifactType.UseCase ? $"UseCase: {h.SimpleRequestName}" : $"Handler: {h.HandlerSimpleName}";

                sb.AppendLine($"        {nodeId}[{label}]:::{style}");

                // Visualizes incoming HTTP requests if the handler has an [Expose] attribute
                if (h.ExposeData != null)
                {
                    string epId = $"EP_{modName}_{h.HandlerSimpleName}";
                    string httpMethod = h.ExposeData.HttpMethod?.ToUpper() ?? "HTTP";
                    string route = h.ExposeData.Route ?? "/";
                    sb.AppendLine($"        {epId}([HTTP {httpMethod} {route}]):::endpoint");
                    sb.AppendLine($"        {epId} ==> {nodeId}");
                }

                // Detect database dependencies via constructor injection (DbContext or Repository pattern)
                if (h.Parameters.Any(p => p.Type.IndexOf("DbContext", StringComparison.OrdinalIgnoreCase) >= 0 || p.Type.IndexOf("Repository", StringComparison.OrdinalIgnoreCase) >= 0))
                {
                    moduleHasDb = true;
                    sb.AppendLine($"        {nodeId} -.-> DB_{modName}");
                }
            }

            // If any handler in the module uses a DB, draw the Database node
            if (moduleHasDb)
                sb.AppendLine($"        DB_{modName}[({modName} Database)]:::db");

            sb.AppendLine("    end");
        }

        sb.AppendLine("");
        sb.AppendLine("    %% --- RECURSIVE CONNECTIONS ---");

        // ---------------------------------------------------------
        // 4. Edge Generation (Connections)
        // ---------------------------------------------------------
        foreach (var kvp in sortedModules)
        {
            string currentModule = kvp.Key;
            var handlers = kvp.Value.Where(x => x.IsHandler);
            string dispatcherNode = $"Dispatcher_{currentModule}";

            foreach (var handler in handlers)
            {
                string sourceId = $"{currentModule}_{handler.HandlerSimpleName}";

                // Connection A: Handler -> Dispatcher
                // If a handler injects the Dispatcher/Mediator, it likely triggers other Commands/Events
                bool usesDispatcher = handler.Parameters.Any(p =>
                    p.Type.IndexOf($"I{currentModule}Dispatcher", StringComparison.OrdinalIgnoreCase) >= 0 ||
                    p.Type.IndexOf("Dispatcher", StringComparison.OrdinalIgnoreCase) >= 0 ||
                    p.Type.IndexOf("IMediator", StringComparison.OrdinalIgnoreCase) >= 0);

                if (usesDispatcher)
                    sb.AppendLine($"    {sourceId} ==> {dispatcherNode}");

                foreach (var param in handler.Parameters)
                {
                    // Connection B: Sync Calls (Module A -> Module B Facade)
                    // Detects injection of other module interfaces (e.g., IStockModule)
                    var simpleTypeName = param.Type.Split('.').Last();
                    if (simpleTypeName.Length > 8 && simpleTypeName.StartsWith("I") && simpleTypeName.EndsWith("Module"))
                    {
                        var targetModName = simpleTypeName.Substring(1, simpleTypeName.Length - 7);
                        // Avoid self-references (Module A calling IModuleAModule)
                        if (!targetModName.Equals(currentModule, StringComparison.OrdinalIgnoreCase))
                        {
                            sb.AppendLine($"    {sourceId} == Sync ==> Facade_{targetModName}");
                        }
                    }

                    // Connection C: External Systems (HTTP Clients)
                    if (param.Type.IndexOf("Client", StringComparison.OrdinalIgnoreCase) >= 0 || param.Type.IndexOf("HttpClient", StringComparison.OrdinalIgnoreCase) >= 0)
                    {
                        string extId = $"Ext_{param.Name}_{currentModule}";
                        string cleanType = param.Type.Split('.').Last();
                        sb.AppendLine($"    {extId}[{cleanType}]:::external");
                        sb.AppendLine($"    {sourceId} -.-> {extId}");
                    }
                }
            }

            // Connection D: Dispatcher -> Internal Commands
            var commands = kvp.Value.Where(x => x.Type == ArtifactType.Command);
            foreach (var cmd in commands)
            {
                string cmdId = $"{currentModule}_{cmd.HandlerSimpleName}";
                sb.AppendLine($"    {dispatcherNode} ==> {cmdId}");
            }

            // Connection E: Dispatcher -> Events -> Async Subscribers
            var ownedEvents = kvp.Value.Where(x => x.Type == ArtifactType.Event && !x.IsHandler);
            foreach (var evt in ownedEvents)
            {
                string evtName = evt.EventSimpleName;
                string evtNodeId = $"Evt_{evtName}";

                // Draw the Event node
                sb.AppendLine($"    {dispatcherNode} ==> {evtNodeId}(({evtName})):::eventNode");

                // Find ALL subscribers across ALL modules for this specific event
                foreach (var consumerKvp in sortedModules)
                {
                    string consumerMod = consumerKvp.Key;
                    var subscribers = consumerKvp.Value.Where(h => h.Type == ArtifactType.Event && h.IsHandler && h.EventSimpleName == evtName);

                    foreach (var sub in subscribers)
                    {
                        string subId = $"{consumerMod}_{sub.HandlerSimpleName}";
                        sb.AppendLine($"    {evtNodeId} ==> |Async| {subId}");
                    }
                }
            }
        }

        sb.AppendLine("*/");

        // Add the generated Mermaid file to the Roslyn context
        context.AddSource("SystemArchitecture_L3_Component.mermaid", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}