using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace Faster.Modulith.Analyzers.Generators;

/// <summary>
/// Generates the internal Dispatcher class for a specific module.
/// The Dispatcher serves as the internal command bus and event publisher, 
/// routing artifacts to their specific handlers within the module boundary.
/// </summary>
internal static class DispatcherGenerator
{
    /// <summary>
    /// Generates the source code for the module's I{ModuleName}Dispatcher interface and its implementation.
    /// </summary>
    /// <param name="context">The source production context to output the generated file.</param>
    /// <param name="commandHandlers">The list of command handlers found in the module.</param>
    /// <param name="events">The list of events defined in the module.</param>
    /// <param name="ctx">The generator context containing module names and settings.</param>
    public static void Generate(SourceProductionContext context, List<HandlerInfo> commandHandlers, List<HandlerInfo> events, GeneratorContext ctx)
    {
        var sb = new StringBuilder();

        // ---------------------------------------------------------
        // 1. Header & Usings
        // ---------------------------------------------------------
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using Faster.Modulith.Contracts;");
        sb.AppendLine("using Faster.Modulith;");

        // ---------------------------------------------------------
        // 2. Interface Definition
        // ---------------------------------------------------------
        sb.AppendLine($@"namespace {ctx.AssemblyName}.Infrastructure;
/// <summary>
/// Internal dispatcher for the {ctx.ModuleName} module.
/// Handles command execution and event publishing within the module boundary.
/// </summary>
internal interface I{ctx.ModuleName}Dispatcher {{");

        // Generate signature for every Command Handler (e.g., PlaceOrder(OrderCommand cmd))
        foreach (var h in commandHandlers)
            sb.AppendLine($"    {(h.ResponseType == "void" ? "ValueTask" : $"ValueTask<{h.ResponseType}>")} {h.SimpleRequestName.Replace("Command", "")}({h.ServiceInterfaceType} command, CancellationToken ct = default);");

        // Generate signatures for Event Publishing (Synchronous/Fire-and-forget & Async)
        foreach (var evt in events)
        {
            string method = evt.SimpleRequestName.Replace("Event", "");
            string args = string.Join(", ", evt.Parameters.Select(p => $"{p.Type} {p.Name}"));
            if (!string.IsNullOrEmpty(args)) args += ", ";
            sb.AppendLine($"    void Publish{method}({args}CancellationToken ct = default);");
            sb.AppendLine($"    Task Publish{method}Async({args}CancellationToken ct = default);");
        }
        sb.AppendLine("}");

        // ---------------------------------------------------------
        // 3. Implementation Class
        // ---------------------------------------------------------
        sb.AppendLine($@"
/// <summary>
/// Default implementation of I{ctx.ModuleName}Dispatcher using standard DI and simple task execution.
/// </summary>
[global::System.Diagnostics.DebuggerStepThrough]
internal sealed class {ctx.ModuleName}Dispatcher : I{ctx.ModuleName}Dispatcher {{
    private readonly System.IServiceProvider _sp;
    public {ctx.ModuleName}Dispatcher(System.IServiceProvider sp) => _sp = sp;");

        // ---------------------------------------------------------
        // 4. Command Implementation (Pipeline Support)
        // ---------------------------------------------------------
        foreach (var h in commandHandlers)
        {
            string methodName = h.SimpleRequestName.Replace("Command", "");
            string retType = h.ResponseType == "void" ? "ValueTask" : $"ValueTask<{h.ResponseType}>";
            string resType = h.ResponseType == "void" ? "int" : h.ResponseType;

            sb.AppendLine($@"
    /// <summary>
    /// Executes the {h.SimpleRequestName} command.
    /// </summary>
    public async {retType} {methodName}({h.ServiceInterfaceType} command, CancellationToken ct) {{");

            // If attributes [EnrichWith(...)] or manual pipelines exist, generate the pipeline wrapper logic
            if (h.PipelineBehaviors.Any() || ctx.HasManualPipelines)
            {
                // 1. Resolve the concrete handler
                // 2. Resolve all applicable pipeline behaviors
                // 3. Wrap them in reverse order (Standard Middleware Pattern)
                sb.AppendLine($@"        var handler = _sp.GetRequiredService<global::Faster.Modulith.Contracts.ICommandHandler<{h.ServiceInterfaceType}, {resType}>>();
        var behaviors = _sp.GetServices<global::Faster.Modulith.Contracts.IPipelineBehavior<{h.ServiceInterfaceType}, {resType}>>().Reverse();
        global::Faster.Modulith.Contracts.RequestHandlerDelegate<{resType}> pipeline = () => handler.Handle(command, ct);
        foreach (var behavior in behaviors) {{ var cb = behavior; var nx = pipeline; pipeline = () => cb.Handle(command, nx, ct); }}
        {(h.ResponseType == "void" ? "await pipeline();" : "return await pipeline();")}");
            }
            else
            {
                // Simple direct resolution and execution if no pipelines are defined
                sb.AppendLine($"        {(h.ResponseType != "void" ? "return " : "")}await _sp.GetRequiredService<global::Faster.Modulith.Contracts.ICommandHandler<{h.ServiceInterfaceType}, {resType}>>().Handle(command, ct);");
            }
            sb.AppendLine("    }");
        }

        // ---------------------------------------------------------
        // 5. Event Implementation (Broadcasting)
        // ---------------------------------------------------------
        foreach (var evt in events)
        {
            string methodName = evt.SimpleRequestName.Replace("Event", "");
            string args = string.Join(", ", evt.Parameters.Select(p => $"{p.Type} {p.Name}"));
            if (!string.IsNullOrEmpty(args)) args += ", ";
            string ctor = string.Join(", ", evt.Parameters.Select(p => p.Name.Replace("@", "")));

            // "Publish" (Fire-and-forget):
            // Runs handlers in a separate Task.Run to avoid blocking the caller. 
            // Exceptions are swallowed to prevent crashing the flow.
            sb.AppendLine($@"
    /// <summary>
    /// Publishes {evt.SimpleRequestName} to all registered subscribers.
    /// </summary>
    public void Publish{methodName}({args}CancellationToken ct = default) {{
        var evt = new {evt.ServiceInterfaceType}({ctor});
        var handlers = _sp.GetServices<global::Faster.Modulith.Contracts.IEventHandler<{evt.ServiceInterfaceType}>>();
        foreach (var h in handlers) _ = Task.Run(async () => {{ try {{ await h.Handle(evt, ct); }} catch {{ }} }}, ct);
    }}

    /// <summary>
    /// Asynchronously publishes {evt.SimpleRequestName} and awaits completion.
    /// </summary>
    public async Task Publish{methodName}Async({args}CancellationToken ct = default) {{
        var evt = new {evt.ServiceInterfaceType}({ctor});
        var handlers = _sp.GetServices<global::Faster.Modulith.Contracts.IEventHandler<{evt.ServiceInterfaceType}>>();
        foreach (var h in handlers) await h.Handle(evt, ct);
    }}");
        }
        sb.AppendLine("}");

        // Add the generated source to the compilation context
        context.AddSource($"{ctx.ModuleName}Dispatcher.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}