using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Faster.Modulith.Analyzers.Generators
{
    /// <summary>
    /// Generates the internal Dispatcher class for a specific module.
    /// </summary>
    /// <remarks>
    /// The Dispatcher serves as the internal command bus and event publisher, 
    /// routing artifacts to their specific handlers within the module boundary.
    /// </remarks>
    internal static class DispatcherGenerator
    {
        /// <summary>
        /// Generates the source code for the module's dispatcher interface, implementation, and extensions.
        /// </summary>
        /// <param name="context">The source production context to output the generated file.</param>
        /// <param name="commandHandlers">The list of command handlers found in the module.</param>
        /// <param name="events">The list of events defined in the module.</param>
        /// <param name="ctx">The generator context containing module metadata.</param>
        public static void Generate(SourceProductionContext context, List<HandlerInfo> commandHandlers, List<HandlerInfo> events, GeneratorContext ctx)
        {
            var sb = new StringBuilder();

            // ==========================================
            // File Header & Imports
            // ==========================================
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using Faster.Modulith.Contracts;");

            // ==========================================
            // Namespace Definition
            // ==========================================
            sb.AppendLine();
            sb.AppendLine($"namespace Module.{ctx.ModuleName};");
            sb.AppendLine();

            // ==========================================
            // Interface Definition (Object-Based Only)
            // ==========================================
            sb.AppendLine($@"/// <summary>
/// Internal dispatcher for the {ctx.ModuleName} module.
/// Handles command execution and event publishing within the module boundary.
/// </summary>
internal interface I{ctx.ModuleName}Dispatcher
{{");

            // Core Command Signatures
            foreach (var h in commandHandlers)
            {
                string methodName = h.SimpleRequestName.Replace("Command", "");
                string retType = h.ResponseType == "void" ? "ValueTask" : $"ValueTask<{h.ResponseType}>";
                sb.AppendLine($"    /// <summary>Executes the {methodName} command.</summary>");
                sb.AppendLine($"    {retType} {methodName}({h.ServiceInterfaceType} command, CancellationToken ct = default);");
            }

            // Core Event Signatures
            foreach (var evt in events)
            {
                string methodName = evt.SimpleRequestName.Replace("Event", "");
                sb.AppendLine($"    /// <summary>Publishes the {methodName} event.</summary>");
                sb.AppendLine($"    void Publish{methodName}({evt.ServiceInterfaceType} @event, CancellationToken ct = default);");
                sb.AppendLine($"    /// <summary>Asynchronously publishes the {methodName} event.</summary>");
                sb.AppendLine($"    Task Publish{methodName}Async({evt.ServiceInterfaceType} @event, CancellationToken ct = default);");
            }

            sb.AppendLine("}");

            // ==========================================
            // Implementation Class
            // ==========================================
            sb.AppendLine($@"
/// <summary>
/// Default implementation of I{ctx.ModuleName}Dispatcher using standard DI and simple task execution.
/// </summary>
[global::System.Diagnostics.DebuggerStepThrough]
internal sealed class {ctx.ModuleName}Dispatcher : I{ctx.ModuleName}Dispatcher
{{
    private readonly global::System.IServiceProvider _sp;

    /// <summary>
    /// Initializes a new instance of the <see cref=""{ctx.ModuleName}Dispatcher""/> class.
    /// </summary>
    public {ctx.ModuleName}Dispatcher(global::System.IServiceProvider sp) => _sp = sp;");

            // Command Implementation
            foreach (var h in commandHandlers)
            {
                string methodName = h.SimpleRequestName.Replace("Command", "");
                string retType = h.ResponseType == "void" ? "ValueTask" : $"ValueTask<{h.ResponseType}>";
                string resType = h.ResponseType == "void" ? "int" : h.ResponseType;

                sb.AppendLine($@"
    /// <summary>
    /// Executes the {h.SimpleRequestName} command.
    /// </summary>
    public async {retType} {methodName}({h.ServiceInterfaceType} command, CancellationToken ct = default)
    {{");

                if (h.PipelineBehaviors.Any() || ctx.HasManualPipelines)
                {
                    sb.AppendLine($@"        var handler = _sp.GetRequiredService<global::Faster.Modulith.Contracts.ICommandHandler<{h.ServiceInterfaceType}, {resType}>>();
        var behaviors = _sp.GetServices<global::Faster.Modulith.Contracts.IPipelineBehavior<{h.ServiceInterfaceType}, {resType}>>().Reverse();
        global::Faster.Modulith.Contracts.RequestHandlerDelegate<{resType}> pipeline = () => handler.Handle(command, ct);
        
        foreach (var behavior in behaviors)
        {{
            var cb = behavior;
            var nx = pipeline;
            pipeline = () => cb.Handle(command, nx, ct);
        }}
        
        {(h.ResponseType == "void" ? "await pipeline();" : "return await pipeline();")}");
                }
                else
                {
                    sb.AppendLine($"        {(h.ResponseType != "void" ? "return " : "")}await _sp.GetRequiredService<global::Faster.Modulith.Contracts.ICommandHandler<{h.ServiceInterfaceType}, {resType}>>().Handle(command, ct);");
                }
                sb.AppendLine("    }");
            }

            // Event Implementation
            foreach (var evt in events)
            {
                string methodName = evt.SimpleRequestName.Replace("Event", "");

                sb.AppendLine($@"
    /// <summary>
    /// Publishes {evt.SimpleRequestName} to all registered subscribers without blocking.
    /// </summary>
    public void Publish{methodName}({evt.ServiceInterfaceType} @event, CancellationToken ct = default)
    {{
        var handlers = _sp.GetServices<global::Faster.Modulith.Contracts.IEventHandler<{evt.ServiceInterfaceType}>>();
        foreach (var h in handlers)
        {{
            _ = Task.Run(async () =>
            {{
                try
                {{
                    await h.Handle(@event, ct);
                }}
                catch (global::System.Exception ex)
                {{
                    global::System.Diagnostics.Debug.WriteLine($""[{{(global::System.DateTime.UtcNow):O}}] Error publishing {evt.SimpleRequestName}: {{ex.Message}}"");
                }}
            }}, ct);
        }}
    }}

    /// <summary>
    /// Asynchronously publishes {evt.SimpleRequestName} and awaits completion.
    /// </summary>
    public async Task Publish{methodName}Async({evt.ServiceInterfaceType} @event, CancellationToken ct = default)
    {{
        var handlers = _sp.GetServices<global::Faster.Modulith.Contracts.IEventHandler<{evt.ServiceInterfaceType}>>();
        foreach (var h in handlers)
        {{
            await h.Handle(@event, ct);
        }}
    }}");
            }

            sb.AppendLine("}");

            // ==========================================
            // Extension Methods (Primitive Arguments)
            // ==========================================
            sb.AppendLine($@"
/// <summary>
/// Provides convenience extension methods for the <see cref=""I{ctx.ModuleName}Dispatcher""/> interface.
/// </summary>
[global::System.Diagnostics.DebuggerStepThrough]
internal static class {ctx.ModuleName}DispatcherExtensions
{{");

            // Extension Commands
            foreach (var h in commandHandlers)
            {
                string methodName = h.SimpleRequestName.Replace("Command", "");
                string retType = h.ResponseType == "void" ? "ValueTask" : $"ValueTask<{h.ResponseType}>";

                string args = string.Join(", ", h.Parameters.Select(p => $"{p.Type} {p.Name}"));
                if (!string.IsNullOrEmpty(args)) args = ", " + args;
                string ctor = string.Join(", ", h.Parameters.Select(p => p.Name.Replace("@", "")));

                sb.AppendLine($@"
    /// <summary>
    /// Executes the {methodName} command using individual parameters.
    /// </summary>
    public static {retType} {methodName}(this I{ctx.ModuleName}Dispatcher dispatcher{args}, CancellationToken ct = default)
    {{
        var command = new {h.ServiceInterfaceType}({ctor});
        return dispatcher.{methodName}(command, ct);
    }}");
            }

            // Extension Events
            foreach (var evt in events)
            {
                string methodName = evt.SimpleRequestName.Replace("Event", "");

                string args = string.Join(", ", evt.Parameters.Select(p => $"{p.Type} {p.Name}"));
                if (!string.IsNullOrEmpty(args)) args = ", " + args;
                string ctor = string.Join(", ", evt.Parameters.Select(p => p.Name.Replace("@", "")));

                sb.AppendLine($@"
    /// <summary>
    /// Publishes the {methodName} event using individual parameters.
    /// </summary>
    public static void Publish{methodName}(this I{ctx.ModuleName}Dispatcher dispatcher{args}, CancellationToken ct = default)
    {{
        var @event = new {evt.ServiceInterfaceType}({ctor});
        dispatcher.Publish{methodName}(@event, ct);
    }}

    /// <summary>
    /// Asynchronously publishes the {methodName} event using individual parameters.
    /// </summary>
    public static Task Publish{methodName}Async(this I{ctx.ModuleName}Dispatcher dispatcher{args}, CancellationToken ct = default)
    {{
        var @event = new {evt.ServiceInterfaceType}({ctor});
        return dispatcher.Publish{methodName}Async(@event, ct);
    }}");
            }

            sb.AppendLine("}");

            // Output the source
            context.AddSource($"{ctx.ModuleName}Dispatcher.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}