using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Faster.Modulith.Analyzers.Generators
{
    /// <summary>
    /// Generates ASP.NET Core minimal API endpoint mappings
    /// for use cases that are marked with the <c>Expose</c> attribute.
    /// </summary>
    /// <remarks>
    /// This generator only runs when:
    /// - The project references ASP.NET Core
    /// - At least one handler contains exposure metadata
    /// 
    /// It generates a partial static endpoint mapping class per module.
    /// </remarks>
    internal static class EndpointGenerator
    {
        /// <summary>
        /// Generates endpoint mapping code for exposed use case handlers.
        /// </summary>
        /// <param name="context">Roslyn source production context used to emit generated code.</param>
        /// <param name="handlers">All discovered handler implementations.</param>
        /// <param name="allItems">All scanned artifacts (definitions + handlers).</param>
        /// <param name="ctx">Shared generator context containing module and environment metadata.</param>
        public static void Generate(
            SourceProductionContext context,
            List<HandlerInfo> handlers,
            List<HandlerInfo> allItems,
            GeneratorContext ctx)
        {
            // Filter handlers that are explicitly exposed via [Expose]
            var exposed = handlers
                .Where(h => h.ExposeData != null)
                .ToList();

            if (!exposed.Any())
            {
                return;
            }

            var sb = new StringBuilder();

            // ==========================================
            // File Header & Imports
            // ==========================================
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using Microsoft.AspNetCore.Builder;");
            sb.AppendLine("using Microsoft.AspNetCore.Http;");
            sb.AppendLine("using Microsoft.AspNetCore.Routing;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using Faster.Modulith.Contracts;");

            // Import the module namespace to resolve I{ModuleName}Api           
            sb.AppendLine($"using Module.{ctx.ModuleName}.Api;");
            sb.AppendLine();

            // ==========================================
            // Namespace & Endpoint Class
            // ==========================================
            sb.AppendLine($@"namespace Module.{ctx.ModuleName};

/// <summary>
/// Endpoint mapping definitions for the {ctx.ModuleName} module.
/// </summary>
/// <remarks>
/// This class is auto-generated and wires exposed use cases
/// into ASP.NET Core minimal API endpoints.
/// </remarks>
[global::System.Diagnostics.DebuggerStepThrough]
public static partial class {ctx.ModuleName}Endpoints
{{
    /// <summary>
    /// Maps all exposed endpoints for the {ctx.ModuleName} module.
    /// </summary>
    /// <param name=""app"">The route builder.</param>
    /// <returns>The configured route builder.</returns>
    public static IEndpointRouteBuilder Map{ctx.ModuleName}Endpoints(this IEndpointRouteBuilder app)
    {{");

            // ==========================================
            // Endpoint Generation Loop
            // ==========================================
            foreach (var h in exposed)
            {
                var expose = h.ExposeData;

                string method = expose.HttpMethod.Substring(0, 1).ToUpper() + expose.HttpMethod.Substring(1).ToLower();
                string route = expose.Route.StartsWith("/") ? expose.Route : "/" + expose.Route;
                string methodName = h.SimpleRequestName.Replace("UseCase", "");

                sb.AppendLine();
                sb.AppendLine(@"        /// <summary>");
                sb.AppendLine($@"        /// Maps the {method.ToUpper()} endpoint at ""{route}"".");
                sb.AppendLine($@"        /// Handled by {h.HandlerSimpleName}.");
                sb.AppendLine(@"        /// </summary>");

                // Minimal API mapping utilizing the direct request object mapping
                sb.AppendLine($@"        app.Map{method}(""{route}"", async ({h.ServiceInterfaceType} request, I{ctx.ModuleName}Api module, CancellationToken ct) => 
        {{");

                // ==========================================
                // Response Handling Logic
                // ==========================================
                if (h.ResponseType == "void" || h.ResponseType.Contains("ValueTask") && !h.ResponseType.Contains("<"))
                {
                    sb.AppendLine($@"            await module.{methodName}(request, ct); 
            return Results.Ok();");
                }
                else
                {
                    sb.AppendLine($@"            var result = await module.{methodName}(request, ct);");

                    if (h.ResponseType.Contains("Result"))
                    {
                        sb.AppendLine("            return result.IsSuccess ? Results.Ok(result) : Results.NotFound(result.Error);");
                    }
                    else
                    {
                        sb.AppendLine("            return Results.Ok(result);");
                    }
                }

                sb.AppendLine($@"        }}).WithTags(""{ctx.ModuleName}"");");
            }

            // ==========================================
            // Finalization
            // ==========================================
            sb.AppendLine("        return app;");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource($"{ctx.ModuleName}Endpoints.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}