using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace Faster.Modulith.Analyzers.Generators;

/// <summary>
/// Generates ASP.NET Core minimal API endpoint mappings
/// for use cases that are marked with the <c>Expose</c> attribute.
/// </summary>
/// <remarks>
/// This generator only runs when:
/// - The project references ASP.NET Core
/// - At least one handler contains exposure metadata
///
/// It generates a partial static endpoint mapping class per module.
/// </remarks>
internal static class EndpointGenerator
{
    /// <summary>
    /// Generates endpoint mapping code for exposed use case handlers.
    /// </summary>
    /// <param name="context">
    /// Roslyn source production context used to emit generated code.
    /// </param>
    /// <param name="handlers">
    /// All discovered handler implementations.
    /// </param>
    /// <param name="allItems">
    /// All scanned artifacts (definitions + handlers).
    /// </param>
    /// <param name="ctx">
    /// Shared generator context containing module and environment metadata.
    /// </param>
    public static void Generate(
        SourceProductionContext context,
        List<HandlerInfo> handlers,
        List<HandlerInfo> allItems,
        GeneratorContext ctx)
    {
        // Filter handlers that are explicitly exposed via [Expose]
        var exposed = handlers
            .Where(h => h.ExposeData != null)
            .ToList();

        if (!exposed.Any())
            return;

        var sb = new StringBuilder();

        // ==========================================
        // File Header & Imports
        // ==========================================

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using Faster.Modulith.Contracts;");

        // ==========================================
        // Namespace & Endpoint Class
        // ==========================================

        sb.AppendLine($@"namespace {ctx.AssemblyName};

/// <summary>
/// Endpoint mapping definitions for the {ctx.ModuleName} module.
/// </summary>
/// <remarks>
/// This class is auto-generated and wires exposed use cases
/// into ASP.NET Core minimal API endpoints.
/// </remarks>
[global::System.Diagnostics.DebuggerStepThrough]
public static partial class {ctx.ModuleName}Endpoints
{{
    /// <summary>
    /// Maps all exposed endpoints for the {ctx.ModuleName} module.
    /// </summary>
    /// <param name=""app"">The route builder.</param>
    /// <returns>The configured route builder.</returns>
    public static IEndpointRouteBuilder Map{ctx.ModuleName}Endpoints(this IEndpointRouteBuilder app)
    {{");

        // ==========================================
        // Endpoint Generation Loop
        // ==========================================

        foreach (var h in exposed)
        {
            // Retrieve the definition (if available) to obtain constructor parameters
            var def = allItems.FirstOrDefault(x =>
                !x.IsHandler &&
                x.Type == ArtifactType.UseCase &&
                x.ServiceInterfaceType == h.ServiceInterfaceType);

            var paramsToUse = def?.Parameters ?? h.Parameters;

            var expose = h.ExposeData;

            string method =
                expose.HttpMethod.Substring(0, 1).ToUpper() +
                expose.HttpMethod.Substring(1).ToLower();

            string route =
                expose.Route.StartsWith("/")
                    ? expose.Route
                    : "/" + expose.Route;

            // Build method argument mapping from request DTO
            string callArgs = string.Join(", ",
                paramsToUse.Select(p =>
                    $"req.{char.ToUpper(p.Name.Replace("@", "")[0]) + p.Name.Replace("@", "").Substring(1)}"));

            if (!string.IsNullOrEmpty(callArgs))
                callArgs += ", ";

            sb.AppendLine();
            sb.AppendLine(@"        /// <summary>");
            sb.AppendLine($@"        /// Maps the {method.ToUpper()} endpoint at ""{route}"".");
            sb.AppendLine($@"        /// Handled by {h.HandlerSimpleName}.");
            sb.AppendLine(@"        /// </summary>");

            sb.AppendLine(
                $@"        app.Map{method}(""{route}"", async ({h.ServiceInterfaceType} req, Faster.Modulith.I{ctx.ModuleName}Module module) => {{");

            // ==========================================
            // Response Handling Logic
            // ==========================================

            if (h.ResponseType == "void" || h.ResponseType.Contains("ValueTask"))
            {
                sb.AppendLine(
                    $@"            await module.{h.SimpleRequestName.Replace("UseCase", "")}({callArgs}CancellationToken.None); 
            return Results.Ok();");
            }
            else
            {
                sb.AppendLine(
                    $@"            var result = await module.{h.SimpleRequestName.Replace("UseCase", "")}({callArgs}CancellationToken.None);");

                if (h.ResponseType.Contains("Result<"))
                {
                    sb.AppendLine(
                        "            return result.IsSuccess ? Results.Ok(result.Value) : Results.NotFound(result.Error);");
                }
                else if (h.ResponseType.EndsWith("Result"))
                {
                    sb.AppendLine(
                        "            return result.IsSuccess ? Results.Ok() : Results.NotFound(result.Error);");
                }
                else
                {
                    sb.AppendLine("            return Results.Ok(result);");
                }
            }

            sb.AppendLine($@"        }}).WithTags(""{ctx.ModuleName}"");");
        }

        // ==========================================
        // Finalization
        // ==========================================

        sb.AppendLine("        return app;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource(
            $"{ctx.ModuleName}Endpoints.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
