using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Text;

namespace Faster.Modulith.Analyzers.Generators;

/// <summary>
/// Generates the public module facade interface.
/// </summary>
/// <remarks>
/// This interface represents the public API surface of a module.
/// It is implemented by the generated module class and consumed by:
/// - Other modules
/// - API layers
/// - External callers
///
/// Each discovered use case definition becomes a strongly-typed method.
/// </remarks>
internal static class InterfaceGenerator
{
    /// <summary>
    /// Generates the module interface for the current module.
    /// </summary>
    /// <param name="context">
    /// Roslyn source production context used to emit generated code.
    /// </param>
    /// <param name="definitions">
    /// All discovered use case definitions (non-handler artifacts).
    /// </param>
    /// <param name="ctx">
    /// Shared generator context containing module metadata.
    /// </param>
    public static void Generate(
        SourceProductionContext context,
        List<HandlerInfo> definitions,
        GeneratorContext ctx)
    {
        var sb = new StringBuilder();

        // ==========================================
        // File Header & Imports
        // ==========================================

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using Faster.Modulith.Contracts;");

        // ==========================================
        // Namespace & Interface Definition
        // ==========================================

        sb.AppendLine($@"namespace Faster.Modulith;

/// <summary>
/// Public API facade for the {ctx.ModuleName} module.
/// </summary>
/// <remarks>
/// Defines the externally accessible operations for the module.
/// Each method corresponds to a discovered use case definition.
/// </remarks>
public interface I{ctx.ModuleName}Module
{{");

        // ==========================================
        // Generate Use Case Method Signatures
        // ==========================================

        foreach (var uc in definitions)
        {
            // Build method parameter list
            string args = string.Join(", ",
                uc.Parameters.Select(p => $"{p.Type} {p.Name}"));

            if (!string.IsNullOrEmpty(args))
                args += ", ";

            sb.AppendLine($@"
    /// <summary>
    /// Executes the {uc.SimpleRequestName.Replace("UseCase", "")} use case.
    /// </summary>
    /// <param name=""ct"">Cancellation token.</param>
    /// <returns>
    /// A <see cref=""ValueTask""/> representing the asynchronous operation.
    /// </returns>
    {(uc.ResponseType == "void"
        ? "ValueTask"
        : $"ValueTask<{uc.ResponseType}>")}
        {uc.SimpleRequestName.Replace("UseCase", "")}({args}CancellationToken ct = default);");
        }

        // ==========================================
        // Finalization
        // ==========================================

        sb.AppendLine("}");

        context.AddSource(
            $"I{ctx.ModuleName}Module.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
