using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Text;

namespace Faster.Modulith.Analyzers.Generators;

/// <summary>
/// Generates the concrete module facade implementation.
/// </summary>
/// <remarks>
/// This generator produces a sealed module class that:
/// - Implements the generated module interface
/// - Delegates all use case execution to the orchestrator
/// - Acts as the entry point for internal and API calls
///
/// The generated class is placed in the <c>Faster.Modulith</c> namespace.
/// </remarks>
internal static class ModuleFacadeGenerator
{
    /// <summary>
    /// Generates the concrete module implementation.
    /// </summary>
    /// <param name="context">
    /// Roslyn source production context used to emit generated code.
    /// </param>
    /// <param name="definitions">
    /// All discovered use case definitions (non-handler artifacts).
    /// </param>
    /// <param name="ctx">
    /// Shared generator context containing module metadata.
    /// </param>
    public static void Generate(
        SourceProductionContext context,
        List<HandlerInfo> definitions,
        GeneratorContext ctx)
    {
        var sb = new StringBuilder();

        // ==========================================
        // File Header & Imports
        // ==========================================

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using Faster.Modulith.Contracts;");

        // ==========================================
        // Namespace & Module Implementation
        // ==========================================

        sb.AppendLine($@"namespace Faster.Modulith;

/// <summary>
/// Concrete implementation of the {ctx.ModuleName} module facade.
/// </summary>
/// <remarks>
/// This class forwards all use case invocations
/// to the underlying <see cref=""IOrchestrator""/>.
/// </remarks>
[global::System.Diagnostics.DebuggerStepThrough]
public sealed class {ctx.ModuleName}Module : I{ctx.ModuleName}Module
{{
    private readonly global::Faster.Modulith.Contracts.IOrchestrator _orchestrator;

    /// <summary>
    /// Initializes a new instance of the <see cref=""{ctx.ModuleName}Module""/> class.
    /// </summary>
    /// <param name=""orchestrator"">
    /// The orchestrator responsible for dispatching requests.
    /// </param>
    public {ctx.ModuleName}Module(global::Faster.Modulith.Contracts.IOrchestrator orchestrator)
        => _orchestrator = orchestrator;");

        // ==========================================
        // Generate Use Case Methods
        // ==========================================

        foreach (var uc in definitions)
        {
            // Build method signature arguments
            string args = string.Join(", ",
                uc.Parameters.Select(p => $"{p.Type} {p.Name}"));

            if (!string.IsNullOrEmpty(args))
                args += ", ";

            // Build constructor argument list for request DTO
            string ctor = string.Join(", ",
                uc.Parameters.Select(p => p.Name.Replace("@", "")));

            sb.AppendLine($@"
    /// <summary>
    /// Executes the {uc.SimpleRequestName.Replace("UseCase", "")} use case.
    /// </summary>
    /// <param name=""ct"">Cancellation token.</param>
    /// <returns>
    /// A <see cref=""ValueTask""/> representing the asynchronous operation.
    /// </returns>
    public {(uc.ResponseType == "void"
        ? "ValueTask"
        : $"ValueTask<{uc.ResponseType}>")}
        {uc.SimpleRequestName.Replace("UseCase", "")}({args}CancellationToken ct = default)
    {{
        var req = new {uc.ServiceInterfaceType}({ctor});

        return _orchestrator.Dispatch<{uc.ServiceInterfaceType}, {uc.ResponseType}>(req, ct);
    }}");
        }

        // ==========================================
        // Finalization
        // ==========================================

        sb.AppendLine("}");

        context.AddSource(
            $"{ctx.ModuleName}Module.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
