using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Faster.Modulith.Analyzers.Generators
{
    /// <summary>
    /// Generates the public module API facade interface, its concrete implementation, and convenience extensions.
    /// </summary>
    /// <remarks>
    /// This generator produces a single file containing:
    /// 1. The public API interface representing the module's core contract.
    /// 2. The sealed partial API class implementation.
    /// 3. The static extension methods for primitive parameters.
    /// </remarks>
    internal static class ModuleApiGenerator
    {
        /// <summary>
        /// Generates the API interface, concrete implementation, and extensions into a single file.
        /// </summary>
        /// <param name="context">Roslyn source production context used to emit generated code.</param>
        /// <param name="definitions">All discovered use case definitions (non-handler artifacts).</param>
        /// <param name="ctx">Shared generator context containing module metadata.</param>
        public static void Generate(
            SourceProductionContext context,
            List<HandlerInfo> definitions,
            GeneratorContext ctx)
        {
            var sb = new StringBuilder();

            AppendHeaderAndUsings(sb);
            sb.AppendLine($"namespace Module.{ctx.ModuleName}.Api;");
            sb.AppendLine();

            AppendInterface(sb, definitions, ctx.ModuleName);
            AppendImplementation(sb, definitions, ctx.ModuleName);
            AppendExtensions(sb, definitions, ctx.ModuleName);

            context.AddSource(
                $"{ctx.ModuleName}Api.g.cs",
                SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        /// <summary>
        /// Generates strictly the public API interface containing the core request-object methods.
        /// This is utilized primarily when compiling the API project boundary.
        /// </summary>
        /// <param name="context">Roslyn source production context used to emit generated code.</param>
        /// <param name="definitions">All discovered use case definitions (non-handler artifacts).</param>
        /// <param name="ctx">Shared generator context containing module metadata.</param>
        public static void GenerateInterface(
            SourceProductionContext context,
            List<HandlerInfo> definitions,
            GeneratorContext ctx)
        {
            var sb = new StringBuilder();

            AppendHeaderAndUsings(sb);
            sb.AppendLine($"namespace Module.{ctx.ModuleName}.Api;");
            sb.AppendLine();

            AppendInterface(sb, definitions, ctx.ModuleName);

            context.AddSource(
                $"I{ctx.ModuleName}Api.g.cs",
                SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        /// <summary>
        /// Appends the standard file header and using directives to the string builder.
        /// </summary>
        private static void AppendHeaderAndUsings(StringBuilder sb)
        {
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using Faster.Modulith.Contracts;");
            sb.AppendLine();
        }

        /// <summary>
        /// Appends the API interface definition to the string builder.
        /// </summary>
        private static void AppendInterface(StringBuilder sb, List<HandlerInfo> definitions, string moduleName)
        {
            sb.AppendLine($@"/// <summary>
/// Public API facade for the {moduleName} module.
/// </summary>
/// <remarks>
/// Defines the externally accessible operations for the module.
/// Each method accepts a strongly-typed request object.
/// </remarks>
public interface I{moduleName}Api
{{");

            foreach (var uc in definitions)
            {
                string methodName = uc.SimpleRequestName.Replace("UseCase", "");
                string returnType = uc.ResponseType == "void" ? "ValueTask" : $"ValueTask<{uc.ResponseType}>";

                sb.AppendLine($@"    /// <summary>
    /// Executes the {methodName} use case.
    /// </summary>
    /// <param name=""request"">The <see cref=""{uc.ServiceInterfaceType}"" /> instance containing the request data.</param>
    /// <param name=""ct"">Cancellation token.</param>
    /// <returns>A <see cref=""ValueTask""/> representing the asynchronous operation.</returns>
    {returnType} {methodName}({uc.ServiceInterfaceType} request, CancellationToken ct = default);");
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        /// <summary>
        /// Appends the sealed partial API implementation class to the string builder.
        /// </summary>
        private static void AppendImplementation(StringBuilder sb, List<HandlerInfo> definitions, string moduleName)
        {
            sb.AppendLine($@"/// <summary>
/// Concrete implementation of the {moduleName} API facade.
/// </summary>
/// <remarks>
/// This class forwards all use case invocations to the underlying <see cref=""IOrchestrator""/>.
/// </remarks>
[global::System.Diagnostics.DebuggerStepThrough]
public sealed partial class {moduleName}Api : I{moduleName}Api
{{
    private readonly global::Faster.Modulith.Contracts.IOrchestrator _orchestrator;

    /// <summary>
    /// Initializes a new instance of the <see cref=""{moduleName}Api""/> class.
    /// </summary>
    /// <param name=""orchestrator"">The orchestrator responsible for dispatching requests.</param>
    public {moduleName}Api(global::Faster.Modulith.Contracts.IOrchestrator orchestrator)
        => _orchestrator = orchestrator;");

            foreach (var uc in definitions)
            {
                string methodName = uc.SimpleRequestName.Replace("UseCase", "");
                string returnType = uc.ResponseType == "void" ? "ValueTask" : $"ValueTask<{uc.ResponseType}>";

                sb.AppendLine($@"
    /// <summary>
    /// Executes the {methodName} use case.
    /// </summary>
    /// <param name=""request"">The <see cref=""{uc.ServiceInterfaceType}"" /> instance containing the request data.</param>
    /// <param name=""ct"">Cancellation token.</param>
    /// <returns>A <see cref=""ValueTask""/> representing the asynchronous operation.</returns>
    public {returnType} {methodName}({uc.ServiceInterfaceType} request, CancellationToken ct = default)
    {{
        return _orchestrator.Dispatch<{uc.ServiceInterfaceType}, {uc.ResponseType}>(request, ct);
    }}");
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        /// <summary>
        /// Appends the static extension methods class to the string builder.
        /// </summary>
        private static void AppendExtensions(StringBuilder sb, List<HandlerInfo> definitions, string moduleName)
        {
            sb.AppendLine($@"/// <summary>
/// Provides convenience extension methods for the <see cref=""I{moduleName}Api""/> interface.
/// </summary>
[global::System.Diagnostics.DebuggerStepThrough]
public static partial class {moduleName}ApiExtensions
{{");

            foreach (var uc in definitions)
            {
                string methodName = uc.SimpleRequestName.Replace("UseCase", "");
                string returnType = uc.ResponseType == "void" ? "ValueTask" : $"ValueTask<{uc.ResponseType}>";

                string args = string.Join(", ", uc.Parameters.Select(p => $"{p.Type} {p.Name}"));
                if (!string.IsNullOrEmpty(args))
                {
                    args = ", " + args;
                }

                string ctor = string.Join(", ", uc.Parameters.Select(p => p.Name.Replace("@", "")));

                sb.AppendLine($@"    /// <summary>
    /// Executes the {methodName} use case using individual parameters.
    /// </summary>
    /// <param name=""api"">The API interface being extended.</param>
    /// {string.Join("\n    /// ", uc.Parameters.Select(p => $"<param name=\"{p.Name.Replace("@", "")}\">The {p.Name.Replace("@", "")} parameter.</param>"))}
    /// <param name=""ct"">Cancellation token.</param>
    /// <returns>A <see cref=""ValueTask""/> representing the asynchronous operation.</returns>
    public static {returnType} {methodName}(this I{moduleName}Api api{args}, CancellationToken ct = default)
    {{
        var req = new {uc.ServiceInterfaceType}({ctor});
        return api.{methodName}(req, ct);
    }}");
            }

            sb.AppendLine("}");
        }
    }
}