using System.Text;
using System.Linq;
using System.Collections.Generic;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text.RegularExpressions;

namespace Faster.Modulith.Generators
{
    [Generator]
    public class OptionsGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var compilation = context.CompilationProvider;

            context.RegisterSourceOutput(compilation, (spc, comp) =>
            {
                // ---------------------------------------------------------
                // GUARD 1: IGNORE MODULE PROJECTS
                // ---------------------------------------------------------
                if (comp.AssemblyName.StartsWith("Module."))
                {
                    return;
                }

                // ---------------------------------------------------------
                // SCAN REFERENCES
                // ---------------------------------------------------------
                var log = new StringBuilder();
                log.AppendLine("// <auto-generated/>");
                log.AppendLine($"// Generator Run on: {comp.AssemblyName}");

                var modules = new List<ModuleInfo>();

                foreach (var assembly in comp.SourceModule.ReferencedAssemblySymbols)
                {
                    var name = assembly.Name;

                    // 1. FILTER: Ignore support libraries
                    if (name.EndsWith(".Api") || name.EndsWith(".Contracts") || name.EndsWith(".Tests"))
                        continue;

                    // 2. CHECK: Must look like a module
                    bool isMatch = name.StartsWith("Module.") || name.Contains(".Module") || name.EndsWith(".Module");
                    if (!isMatch) continue;

                    // 3. EXTRACT NAME (Module.Kitchen -> Kitchen)
                    var match = Regex.Match(name, @"\.Modules?\.(\w+)", RegexOptions.IgnoreCase);
                    var simpleName = match.Success ? match.Groups[1].Value : name.Split('.').Last();

                    if (simpleName.Equals("Module", System.StringComparison.OrdinalIgnoreCase))
                    {
                        var parts = name.Split('.');
                        if (parts.Length > 1) simpleName = parts[parts.Length - 2];
                    }

                    modules.Add(new ModuleInfo
                    {   Namespace = name + ".Infrastructure",
                        Name = simpleName
                    });
                }

                // ---------------------------------------------------------
                // GUARD 2: IF NO MODULES FOUND, STOP
                // ---------------------------------------------------------
                if (modules.Count == 0) return;

                // ---------------------------------------------------------
                // CODE GENERATION
                // ---------------------------------------------------------
                var sb = new StringBuilder();
                sb.Append(log.ToString());

                sb.AppendLine("using System;");
                sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
                sb.AppendLine("using Microsoft.Extensions.Configuration;");
                sb.AppendLine("using Faster.Modulith.Contracts;");
                sb.AppendLine("using Faster.Modulith;");

                // We don't necessarily need 'using Module.Kitchen' if the Options class is in Faster.Modulith namespace
                // But we add them just in case specific types are needed.
                foreach (var mod in modules)
                {
                    sb.AppendLine($"using {mod.Namespace};");
                }

                sb.AppendLine(@"
namespace Faster.Modulith
{
    public static partial class FasterModulithHostExtensions
    {
        public static IServiceCollection AddModulith(
            this IServiceCollection services, 
            IConfiguration configuration,
            Action<FasterModulithOptions> configure)
        {
            services.AddScoped<IOrchestrator, Orchestrator>();
            var options = new FasterModulithOptions(services, configuration);
            configure?.Invoke(options);
            return services;
        }
");

                foreach (var mod in modules)
                {
                    // UPDATED: Now accepts Action<KitchenOptions>
                    sb.AppendLine($@"
        public static FasterModulithOptions Add{mod.Name}(
            this FasterModulithOptions options, 
            Action<{mod.Name}Options> configure = null)
        {{
            // 1. Automatic Binding: Bind 'Kitchen' section from appsettings.json
            options.Services.Configure<{mod.Name}Options>(options.Configuration.GetSection(""{mod.Name}""));

            // 2. Manual Configuration & Registration
            options.Services.Add{mod.Name}Module(configure);
            
            return options;
        }}");
                }

                sb.AppendLine("    }\n}");

                spc.AddSource("FasterModulithHostExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            });
        }

        private class ModuleInfo
        {
            public string Namespace { get; set; }
            public string Name { get; set; }
        }
    }
}