using System;
using System.Text;
using System.Linq;
using System.Collections.Generic;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text.RegularExpressions;

namespace Faster.Modulith.Generators
{
    /// <summary>
    /// Generates host extension methods for registering referenced modules
    /// into the dependency injection container.
    /// </summary>
    /// <remarks>
    /// This generator scans referenced assemblies and:
    /// 
    /// - Detects assemblies that follow the "Module.*" naming convention
    /// - Generates Add{ModuleName} extension methods
    /// - Automatically binds configuration sections
    /// - Registers module infrastructure
    ///
    /// It executes exclusively for valid host targets and will generate the base 
    /// extensions even if no referenced modules are currently found.
    /// </remarks>
    [Generator]
    public class OptionsGenerator : IIncrementalGenerator
    {
        /// <summary>
        /// Configures the incremental generator pipeline.
        /// </summary>
        /// <param name="context">
        /// The incremental generator initialization context.
        /// </param>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var provider = context.CompilationProvider
                .Combine(context.AnalyzerConfigOptionsProvider);

            context.RegisterSourceOutput(provider, (spc, source) =>
            {
                var compilation = source.Left;
                var options = source.Right;

                // 1. Check OutputKind for Executable Binaries
                bool isExecutable =
                    compilation.Options.OutputKind == OutputKind.ConsoleApplication ||
                    compilation.Options.OutputKind == OutputKind.WindowsApplication;

                // 2. Check MSBuild Properties for Web SDK
                bool isWebSdk = options.GlobalOptions.TryGetValue("build_property.UsingMicrosoftNETSdkWeb", out var webSdkVal)
                                && webSdkVal.Equals("true", StringComparison.OrdinalIgnoreCase);

                // 3. Project Naming Convention Check
                bool isApiProject = compilation.AssemblyName != null &&
                                    compilation.AssemblyName.EndsWith(".Api", StringComparison.OrdinalIgnoreCase);

                bool isTestProject = compilation.AssemblyName != null &&
                                     compilation.AssemblyName.Contains(".Test", StringComparison.OrdinalIgnoreCase) ||
                                     compilation.AssemblyName.Contains(".Tests", StringComparison.OrdinalIgnoreCase);

                // Determine if this is a valid host target
                if (!isExecutable && !isWebSdk || isApiProject || isTestProject)
                {
                    return;
                }

                // ---------------------------------------------------------
                // SCAN REFERENCED ASSEMBLIES
                // ---------------------------------------------------------

                var log = new StringBuilder();
                log.AppendLine("// <auto-generated/>");
                log.AppendLine($"// Generator Run on: {compilation.AssemblyName} at {DateTime.UtcNow:O}");

                var modules = new List<ModuleInfo>();

                foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols)
                {
                    var name = assembly.Name;

                    // 1. FILTER: Ignore support libraries
                    if (name.EndsWith(".Api", StringComparison.OrdinalIgnoreCase) ||
                        name.EndsWith(".Contracts", StringComparison.OrdinalIgnoreCase) ||
                        name.EndsWith(".Tests", StringComparison.OrdinalIgnoreCase))
                        continue;

                    // 2. CHECK: Must follow module naming pattern
                    bool isMatch =
                        name.StartsWith("Module.") ||
                        name.Contains(".Module") ||
                        name.EndsWith(".Module");

                    if (!isMatch)
                        continue;

                    // 3. EXTRACT SIMPLE MODULE NAME
                    var match = Regex.Match(name, @"\.Modules?\.(\w+)", RegexOptions.IgnoreCase);
                    var simpleName = match.Success
                        ? match.Groups[1].Value
                        : name.Split('.').Last();

                    // Edge case: avoid returning "Module" as module name
                    if (simpleName.Equals("Module", StringComparison.OrdinalIgnoreCase))
                    {
                        var parts = name.Split('.');
                        if (parts.Length > 1)
                            simpleName = parts[parts.Length - 2];
                    }

                    modules.Add(new ModuleInfo
                    {
                        Namespace = name + ".Infrastructure",
                        Name = simpleName
                    });
                }

                // ---------------------------------------------------------
                // CODE GENERATION
                // ---------------------------------------------------------

                var sb = new StringBuilder();
                sb.Append(log.ToString());

                sb.AppendLine("using System;");
                sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
                sb.AppendLine("using Microsoft.Extensions.Configuration;");
                sb.AppendLine("using Faster.Modulith.Contracts;");
                sb.AppendLine("using Faster.Modulith;");

                // Include infrastructure namespaces for each discovered module
                foreach (var mod in modules)
                {
                    sb.AppendLine($"using {mod.Namespace};");
                }

                sb.AppendLine(@"
namespace Faster.Modulith
{
    /// <summary>
    /// Extension methods for configuring the Faster.Modulith host.
    /// </summary>
    public static partial class FasterModulithHostExtensions
    {
        /// <summary>
        /// Registers the modulith core services.
        /// </summary>
        /// <param name=""services"">Service collection.</param>
        /// <param name=""configuration"">Application configuration.</param>
        /// <param name=""configure"">Optional configuration callback.</param>
        /// <returns>The updated service collection.</returns>
        public static IServiceCollection AddModulith(
            this IServiceCollection services, 
            IConfiguration configuration,
            Action<FasterModulithOptions> configure = null)
        {
            services.AddScoped<IOrchestrator, Orchestrator>();

            var options = new FasterModulithOptions(services, configuration);
            configure?.Invoke(options);

            return services;
        }
");

                // ---------------------------------------------------------
                // MODULE REGISTRATION METHODS
                // ---------------------------------------------------------

                foreach (var mod in modules)
                {
                    sb.AppendLine($@"
        /// <summary>
        /// Registers the {mod.Name} module.
        /// </summary>
        /// <param name=""options"">The modulith options builder.</param>
        /// <param name=""configure"">
        /// Optional configuration delegate for {mod.Name}Options.
        /// </param>
        /// <returns>The updated modulith options.</returns>
        public static FasterModulithOptions Add{mod.Name}(
            this FasterModulithOptions options, 
            Action<{mod.Name}Options> configure = null)
        {{
            // 1. Automatic configuration binding
            options.Services.Configure<{mod.Name}Options>(
                options.Configuration.GetSection(""{mod.Name}""));

            // 2. Infrastructure registration
            options.Services.Add{mod.Name}Module(configure);
            
            return options;
        }}");
                }

                sb.AppendLine(@"    }
}");

                spc.AddSource(
                    "FasterModulithHostExtensions.g.cs",
                    SourceText.From(sb.ToString(), Encoding.UTF8));
            });
        }

        /// <summary>
        /// Internal metadata holder for discovered modules.
        /// </summary>
        private class ModuleInfo
        {
            /// <summary>
            /// Infrastructure namespace of the module.
            /// </summary>
            public string Namespace { get; set; }

            /// <summary>
            /// Simple module name (e.g. Kitchen, Orders).
            /// </summary>
            public string Name { get; set; }
        }
    }
}