using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace Faster.Modulith.Analyzers.Generators;

/// <summary>
/// Generates dependency injection registration code for a Modulith module.
/// 
/// This source generator creates:
/// - Module Options class
/// - Module registration extension method
/// - Handler registrations (Command / UseCase / Event)
/// - Pipeline behavior registrations
/// - Optional infrastructure hook
/// </summary>
internal static class RegistrationGenerator
{
    /// <summary>
    /// Generates the module registration source file.
    /// </summary>
    /// <param name="context">
    /// Roslyn source production context used to emit generated source code.
    /// </param>
    /// <param name="handlers">
    /// Collection of discovered handlers (Commands, UseCases, Events) 
    /// including their metadata and pipeline behaviors.
    /// </param>
    /// <param name="ctx">
    /// Generator context containing assembly and module metadata.
    /// </param>
    public static void Generate(SourceProductionContext context, List<HandlerInfo> handlers, GeneratorContext ctx)
    {
        // StringBuilder used to compose the generated C# source code.
        var sb = new StringBuilder();

        // Standard auto-generated file header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Faster.Modulith;");

        // Begin generated namespace and types
        sb.AppendLine($@"namespace {ctx.AssemblyName}.Infrastructure;

        /// <summary>
        /// Configuration options for the {ctx.ModuleName} module.
        /// 
        /// Consumers can configure module-specific behavior via the
        /// Add{ctx.ModuleName}Module extension method.
        /// </summary>
        [global::System.Diagnostics.DebuggerStepThrough]
        public partial class {ctx.ModuleName}Options {{ }}

        /// <summary>
        /// Extension methods for registering the {ctx.ModuleName} module services.
        /// </summary>
        [global::System.Diagnostics.DebuggerStepThrough]
        public static partial class {ctx.ModuleName}Extensions {{

            /// <summary>
            /// Adds the {ctx.ModuleName} module to the service collection.
            /// 
            /// This method registers:
            /// - Module dispatcher
            /// - Optional module facade (if use cases exist)
            /// - All discovered handlers
            /// - Pipeline behaviors
            /// - Additional infrastructure via partial hook
            /// </summary>
            /// <param name=""services"">The service collection.</param>
            /// <param name=""configure"">
            /// Optional configuration delegate for {ctx.ModuleName}Options.
            /// </param>
            /// <returns>The updated service collection.</returns>
            public static IServiceCollection Add{ctx.ModuleName}Module(
                this IServiceCollection services, 
                Action<{ctx.ModuleName}Options> configure = null)
            {{
                // Apply module configuration if provided
                if (configure != null) services.Configure(configure);

                // Register the module dispatcher
                services.AddScoped<I{ctx.ModuleName}Dispatcher, {ctx.ModuleName}Dispatcher>();

                // Register module facade only if at least one UseCase exists
                {(handlers.Any(h => h.Type == ArtifactType.UseCase)
                    ? $"services.AddScoped<I{ctx.ModuleName}Module, {ctx.ModuleName}Module>();"
                    : "")}");

        // ---------------------------------------------
        // Register all discovered handlers
        // ---------------------------------------------
        foreach (var h in handlers)
        {
            // Determine the correct contract interface based on artifact type
            string type = h.Type switch
            {
                // Command handlers return int if response type is void (internal convention)
                ArtifactType.Command =>
                    $"global::Faster.Modulith.Contracts.ICommandHandler<{h.ServiceInterfaceType}, {(h.ResponseType == "void" ? "int" : h.ResponseType)}>",

                // Use case handlers
                ArtifactType.UseCase =>
                    $"global::Faster.Modulith.Contracts.IUseCaseHandler<{h.ServiceInterfaceType}, {h.ResponseType}>",

                // Event handlers (default)
                _ =>
                    $"global::Faster.Modulith.Contracts.IEventHandler<{h.ServiceInterfaceType}>"
            };

            // Register handler implementation with scoped lifetime
            sb.AppendLine($"        services.AddScoped<{type}, {h.ImplementationType}>();");
        }

        // ---------------------------------------------
        // Register pipeline behaviors (if any)
        // ---------------------------------------------
        var behaviors = handlers.Where(h => h.PipelineBehaviors.Any()).ToList();
        if (behaviors.Any())
        {
            sb.AppendLine("        // Pipelines");

            foreach (var h in behaviors)
            {
                foreach (var b in h.PipelineBehaviors)
                {
                    // Resolve return type (void mapped to int)
                    string res = h.ResponseType == "void" ? "int" : h.ResponseType;

                    // Replace open generic placeholder "<,>" if present
                    string final = b.Contains("<,>")
                        ? b.Replace("<,>", $"<{h.ServiceInterfaceType}, {res}>")
                        : b;

                    // Register pipeline behavior
                    sb.AppendLine(
                        $"        services.AddScoped<global::Faster.Modulith.Contracts.IPipelineBehavior<{h.ServiceInterfaceType}, {res}>, {final}>();");
                }
            }
        }

        // Call optional partial infrastructure hook
        sb.AppendLine("        AddInfrastructure(services);");

        // Return IServiceCollection for fluent chaining
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");

        sb.AppendLine(@"
            /// <summary>
            /// Partial method to allow manual registration of additional infrastructure services.
            /// 
            /// This method can be implemented manually in a separate partial class
            /// without modifying the generated file.
            /// </summary>
            static partial void AddInfrastructure(IServiceCollection services);");

        sb.AppendLine("}");

        // Emit generated source file into compilation
        context.AddSource(
            $"{ctx.ModuleName}Extensions.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
