using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Faster.Modulith.Analyzers.Generators
{
    /// <summary>
    /// Generates dependency injection registration code for a Modulith module.
    /// </summary>
    /// <remarks>
    /// This source generator creates two separate files:
    /// - Module Options class for configuration binding.
    /// - Module registration extension method (wiring handlers, pipelines, and the internal dispatcher).
    /// </remarks>
    internal static class RegistrationGenerator
    {
        /// <summary>
        /// Generates the module options and registration extension classes.
        /// </summary>
        /// <param name="context">Roslyn source production context used to emit generated source code.</param>
        /// <param name="handlers">Collection of discovered handlers (Commands, UseCases, Events).</param>
        /// <param name="ctx">Generator context containing assembly and module metadata.</param>
        public static void Generate(SourceProductionContext context, List<HandlerInfo> handlers, GeneratorContext ctx)
        {
            GenerateOptions(context, ctx);
            GenerateExtensions(context, handlers, ctx);
        }

        /// <summary>
        /// Generates the partial options class used for configuration section binding.
        /// </summary>
        private static void GenerateOptions(SourceProductionContext context, GeneratorContext ctx)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine($"// Generated at: {DateTime.UtcNow:O}");
            sb.AppendLine();
            sb.AppendLine($"namespace Module.{ctx.ModuleName}.Infrastructure;");
            sb.AppendLine();
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// Configuration options for the {ctx.ModuleName} module.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("/// <remarks>");
            sb.AppendLine($"/// Consumers can configure module-specific behavior via the Add{ctx.ModuleName}Module extension method.");
            sb.AppendLine("/// </remarks>");
            sb.AppendLine("[global::System.Diagnostics.DebuggerStepThrough]");
            sb.AppendLine($"public partial class {ctx.ModuleName}Options");
            sb.AppendLine("{");
            sb.AppendLine("}");

            context.AddSource(
                $"{ctx.ModuleName}Options.g.cs",
                SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        /// <summary>
        /// Generates the DI container extension methods for the module.
        /// </summary>
        private static void GenerateExtensions(SourceProductionContext context, List<HandlerInfo> handlers, GeneratorContext ctx)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine($"// Generated at: {DateTime.UtcNow:O}");
            sb.AppendLine("using System;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("using Faster.Modulith.Contracts;");
            sb.AppendLine($"using Module.{ctx.ModuleName};");
            sb.AppendLine();
            sb.AppendLine($"namespace Module.{ctx.ModuleName}.Infrastructure;");
            sb.AppendLine();
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// Extension methods for registering the {ctx.ModuleName} module services.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("[global::System.Diagnostics.DebuggerStepThrough]");
            sb.AppendLine($"public static partial class {ctx.ModuleName}Extensions");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// Adds the {ctx.ModuleName} module to the service collection.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    /// <param name=\"services\">The service collection.</param>");
            sb.AppendLine($"    /// <param name=\"configure\">Optional configuration delegate for {ctx.ModuleName}Options.</param>");
            sb.AppendLine("    /// <returns>The updated service collection.</returns>");
            sb.AppendLine($"    public static IServiceCollection Add{ctx.ModuleName}Module(");
            sb.AppendLine("        this IServiceCollection services, ");
            sb.AppendLine($"        Action<{ctx.ModuleName}Options> configure = null)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (configure != null)");
            sb.AppendLine("        {");
            sb.AppendLine("            services.Configure(configure);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        // Register the internal module dispatcher");
            sb.AppendLine($"        services.AddScoped<I{ctx.ModuleName}Dispatcher, {ctx.ModuleName}Dispatcher>();");
            sb.AppendLine();

            // ---------------------------------------------
            // Register all discovered handlers
            // ---------------------------------------------
            foreach (var h in handlers)
            {
                string type = h.Type switch
                {
                    ArtifactType.Command => $"global::Faster.Modulith.Contracts.ICommandHandler<{h.ServiceInterfaceType}, {(h.ResponseType == "void" ? "int" : h.ResponseType)}>",
                    ArtifactType.UseCase => $"global::Faster.Modulith.Contracts.IUseCaseHandler<{h.ServiceInterfaceType}, {h.ResponseType}>",
                    _ => $"global::Faster.Modulith.Contracts.IEventHandler<{h.ServiceInterfaceType}>"
                };

                sb.AppendLine($"        services.AddScoped<{type}, {h.ImplementationType}>();");
            }

            // ---------------------------------------------
            // Register pipeline behaviors (if any)
            // ---------------------------------------------
            var behaviors = handlers.Where(h => h.PipelineBehaviors.Any()).ToList();
            if (behaviors.Any())
            {
                sb.AppendLine();
                sb.AppendLine("        // Pipelines");

                foreach (var h in behaviors)
                {
                    foreach (var b in h.PipelineBehaviors)
                    {
                        string res = h.ResponseType == "void" ? "int" : h.ResponseType;
                        string final = b.Contains("<,>") ? b.Replace("<,>", $"<{h.ServiceInterfaceType}, {res}>") : b;

                        sb.AppendLine($"        services.AddScoped<global::Faster.Modulith.Contracts.IPipelineBehavior<{h.ServiceInterfaceType}, {res}>, {final}>();");
                    }
                }
            }

            // Call optional partial infrastructure hook
            sb.AppendLine();
            sb.AppendLine("        AddInfrastructure(services);");
            sb.AppendLine();
            sb.AppendLine("        return services;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Partial method to allow manual registration of additional infrastructure services.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    /// <param name=\"services\">The service collection.</param>");
            sb.AppendLine("    static partial void AddInfrastructure(IServiceCollection services);");
            sb.AppendLine("}");

            context.AddSource(
                $"{ctx.ModuleName}Extensions.g.cs",
                SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}