using Microsoft.CodeAnalysis;

namespace Faster.Modulith.Analyzers.Generators;

[Generator]
public class TestVisibilityGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider);

        context.RegisterSourceOutput(provider, (spc, source) =>
        {
            var compilation = source.Left;
            var options = source.Right;
            var assemblyName = compilation.AssemblyName;

            if (string.IsNullOrEmpty(assemblyName)) return;
            if (!assemblyName.Contains(".Module.")) return;

            // 🔑 STRONG NAME SUPPORT
            // Read "build_property.ModularMonolithTestPublicKey" from .csproj
            options.GlobalOptions.TryGetValue("build_property.ModularMonolithTestPublicKey", out var publicKey);

            string suffix = string.IsNullOrWhiteSpace(publicKey)
                ? ""
                : $", PublicKey={publicKey}";

            string sourceCode = $@"// <auto-generated/>
using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo(""{assemblyName}.Tests{suffix}"")]
[assembly: InternalsVisibleTo(""{assemblyName}.UnitTests{suffix}"")]
[assembly: InternalsVisibleTo(""{assemblyName}.IntegrationTests{suffix}"")]
";
            spc.AddSource("InternalsVisibleTo.g.cs", sourceCode);
        });
    }
}