using Microsoft.CodeAnalysis;

namespace Faster.Modulith.Analyzers.Generators;

/// <summary>
/// Generates <see cref="System.Runtime.CompilerServices.InternalsVisibleToAttribute"/> 
/// declarations automatically for Modulith module assemblies.
///
/// This allows test projects to access internal members without requiring
/// manual InternalsVisibleTo declarations in each module.
///
/// Behavior:
/// - Only activates for assemblies containing "Module." in their name
/// - Supports strong-named assemblies via PublicKey configuration
/// - Automatically grants visibility to:
///     - {Assembly}.Tests
///     - {Assembly}.UnitTests
///     - {Assembly}.IntegrationTests
/// </summary>
[Generator]
public class TestVisibilityGenerator : IIncrementalGenerator
{
    /// <summary>
    /// Initializes the incremental source generator pipeline.
    /// </summary>
    /// <param name="context">
    /// Provides access to compilation and analyzer configuration.
    /// </param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Combine compilation information with MSBuild analyzer config options
        // This allows access to:
        // - Assembly name
        // - Custom build properties from the .csproj
        var provider = context.CompilationProvider
                              .Combine(context.AnalyzerConfigOptionsProvider);

        context.RegisterSourceOutput(provider, (spc, source) =>
        {
            var compilation = source.Left;
            var options = source.Right;

            // Retrieve assembly name
            var assemblyName = compilation.AssemblyName;

            // Skip generation if:
            // - Assembly name is null/empty
            // - Assembly does not follow Modulith naming convention
            if (string.IsNullOrEmpty(assemblyName)) return;
            if (!assemblyName.Contains("Module.")) return;

            // ------------------------------------------------------------
            // 🔑 STRONG NAME SUPPORT
            //
            // If the module is strong-named, InternalsVisibleTo must include
            // the full public key (NOT the token).
            //
            // This value is expected to be defined in the .csproj:
            //
            // <PropertyGroup>
            //   <ModularMonolithTestPublicKey>002400000480000094...</ModularMonolithTestPublicKey>
            // </PropertyGroup>
            //
            // It is accessed through:
            // build_property.ModularMonolithTestPublicKey
            // ------------------------------------------------------------
            options.GlobalOptions.TryGetValue(
                "build_property.ModularMonolithTestPublicKey",
                out var publicKey);

            // Append PublicKey only if provided
            string suffix = string.IsNullOrWhiteSpace(publicKey)
                ? ""
                : $", PublicKey={publicKey}";

            // Generate assembly-level InternalsVisibleTo attributes
            string sourceCode = $@"// <auto-generated/>
using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo(""{assemblyName}.Tests{suffix}"")]
[assembly: InternalsVisibleTo(""{assemblyName}.UnitTests{suffix}"")]
[assembly: InternalsVisibleTo(""{assemblyName}.IntegrationTests{suffix}"")]
";

            // Emit generated source file into the compilation
            spc.AddSource("InternalsVisibleTo.g.cs", sourceCode);
        });
    }
}
