<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.2" />
    <PackageReference Include="Faster.Modulith.Contracts" Version="1.0.1" />
    <PackageReference Include="Faster.Modulith.Analyzers" Version="1.0.1" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Application\CommandHandlers\" />
    <Folder Include="Application\EventHandlers\" />
    <Folder Include="Contracts\" />
    <Folder Include="Infrastructure\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Module.Ordering.Api\Module.Ordering.Api.csproj" />
  </ItemGroup>
</Project>

